$py = "import subprocess, json`n"
$py += "def run(cmd):`n"
$py += "    return subprocess.check_output(cmd, shell=True, stderr=subprocess.DEVNULL).decode()`n"
$py += 'print("=== QDRANT POINTS ===")' + "`n"
$py += 'for c in ["ganjuur_frames","ganjuur_genealogy","ganjuur_words"]:' + "`n"
$py += '    try:' + "`n"
$py += '        r = run("curl -fsS http://127.0.0.1:6333/collections/" + c)' + "`n"
$py += '        n = json.loads(r).get("result",{}).get("points_count","0")' + "`n"
$py += '    except Exception as e:' + "`n"
$py += '        n = "ERR"' + "`n"
$py += '    print("  " + c + ": " + str(n) + " points")' + "`n"
$py += 'print("")' + "`n"
$py += 'print("=== INGEST TAIL ===")' + "`n"
$py += 'try:' + "`n"
$py += '    print(run("tail -20 /home/trinity/ganjuur/bdrc_ingest.log"))' + "`n"
$py += 'except Exception as e:' + "`n"
$py += '    print("log err: " + str(e))' + "`n"
$py += 'print("")' + "`n"
$py += 'print("=== DB_FRAMES ===")' + "`n"
$py += 'print("  " + run("find /home/trinity/ganjuur/data/ganjuur_crops/db_frames -type f | wc -l").strip() + " files")' + "`n"
$py += 'print("  " + run("du -sh /home/trinity/ganjuur/data/ganjuur_crops/db_frames").strip())' + "`n"
$py += 'print("")' + "`n"
$py += 'print("=== CROPS REFS IN LONGCAT ===")' + "`n"
$py += 'src = open("/home/trinity/ganjuur/longcat.py").read()' + "`n"
$py += 'for i, line in enumerate(src.splitlines(), 1):' + "`n"
$py += '    if any(kw in line for kw in ["CROPS_DIR","db_frames","/crops","CROPS"]):' + "`n"
$py += '        print(str(i) + ": " + line.strip())' + "`n"
$b = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($py))
Write-Output $b
